-- =====================================================
-- Run Aggregation Procedures to Populate Dashboard Tables
-- =====================================================

USE DATABASE MANUFACTURING_DEMO;
USE WAREHOUSE COMPUTE_WH;

-- Run all aggregation procedures to populate dashboard data
CALL UTILITIES.CALCULATE_EQUIPMENT_PERFORMANCE();
CALL UTILITIES.CALCULATE_PRODUCTION_METRICS();
CALL UTILITIES.CALCULATE_QUALITY_SUMMARY();
CALL UTILITIES.UPDATE_REALTIME_DASHBOARD();

-- Verify data was created
SELECT 'AGG_EQUIPMENT_PERFORMANCE' as table_name, COUNT(*) as row_count 
FROM AGGREGATION.AGG_EQUIPMENT_PERFORMANCE
UNION ALL
SELECT 'AGG_PRODUCTION_METRICS', COUNT(*) 
FROM AGGREGATION.AGG_PRODUCTION_METRICS
UNION ALL  
SELECT 'AGG_QUALITY_SUMMARY', COUNT(*) 
FROM AGGREGATION.AGG_QUALITY_SUMMARY
UNION ALL
SELECT 'AGG_PREDICTIVE_MAINTENANCE', COUNT(*) 
FROM AGGREGATION.AGG_PREDICTIVE_MAINTENANCE
UNION ALL
SELECT 'AGG_REALTIME_DASHBOARD', COUNT(*) 
FROM AGGREGATION.AGG_REALTIME_DASHBOARD; 